version: '2'

services:

  kibana:
    image:  docker.artifactory.weedon.org.au/redwyvern/kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
